### ISSUE TITLE
github action openvpn

### ISSUE THREAD

**Issue by naem1023** [boostcampaitech2/final-project-level3-nlp-09#45]
action 오류로 인해 close
# Ref
- https://github.com/golfzaptw/action-connect-ovpn
- https://github.com/marketplace/actions/connect-vpn
- https://github.com/marketplace/actions/openvpn-connect
- https://grrr.tech/posts/2021/github-actions-openvpn/
# TODO
- [x] aws ec2 instance에 openvpn 설치
- [ ] openvpn action 설정
- [ ] github action에서 nipa server 접속 가능한지 확인
